### ISSUE TITLE
Issue with using single days

### ISSUE THREAD

**Issue by icuzz96** [sk8Guerra/loretta#3]
Hi, I'm trying to set up message for certain days, using this:

const events = [
  {
    message: "Sunday test",
    days: days.SUNDAY,
    hours: 14,
    minutes: 30,
    seconds: 0,
  }, 
];

This is the error i get: 
\loretta-master\src\bot\bot.js:41
      config.days.forEach((day) => {
                  ^

TypeError: config.days.forEach is not a function
    at C:\Users\rocket\Downloads\loretta-master\src\bot\bot.js:41:19
    at Array.forEach (<anonymous>)
    at Bot.createEvents (C:\Users\rocket\Downloads\loretta-master\src\bot\bot.js:40:12)
    at Server.<anonymous> (C:\Users\rocket\Downloads\loretta-master\index.js:20:19)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitListeningNT (node:net:1775:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v19.4.0

Any help?

**Comment by sk8Guerra** [comment]
@icuzz96 Sorry for the late replay. Will check what could be happening.

**Comment by sk8Guerra** [comment]
Hi @icuzz96 in the case that you are still having the problem, you need to wrap `single days` into an array.

```js
const events = [{
  message: "Sunday test",
  days: [days.SUNDAY],
  hours: 14,
  minutes: 30,
  seconds: 0,
}];
```

Note the brackets (`[]`) in the `days` prop.
